### ISSUE TITLE
Path Declarations

### ISSUE THREAD

**Issue by micybusy** [pehlicd/Slack-DND#5]
We have these path declarations on `slack-dnd.py` script. However, these path declarations will raise an exception unless the machine that runs the code has a Unix OS, i.e., Windows root path is declared with a backslash ( \ ).

```
# Initial setup
home = str(Path.home())
slack_dnd_dir = Path(home + "/.slack-dnd")
conf = Path(home + "/.slack-dnd/config.json")
```

Cross-platform-compatibility, however, is always nice 🙂

**Comment by pehlicd** [comment]
Hey, thanks for the issue. Slack DND is a simple MacOS status bar application, as mentioned in the README. So it's not aimed at any other platforms than MacOS. This is why I used the `rumps` library in the project. As much as I would like to support other platforms, rumps is a specific library for developing MacOS applications.

See doc: https://github.com/jaredks/rumps
